version: "2"
services:
  qiskit-service-0.25.0:
    image: qiskit-0.25.0
    container_name: qiskit-container-0.25.0
    build:
      context: ./
      dockerfile: ./Dockerfile_prod # production environment
#      dockerfile: ./Dockerfile_dev # development environment
    environment:
#      - QISKIT_API_TOKEN=
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./qiskit-jupyter:/home/qiskit/qiskit-jupyter
    ports:
      - 8889:8889
    restart: unless-stopped
