version: "2"
services:
  qiskit-service:
    image: qiskit
    container_name: qiskit-container
    build:
      context: ./
      dockerfile: ./Dockerfile_prod # production environment
#      dockerfile: ./Dockerfile_dev # development environment
    environment:
#      - QISKIT_USER=
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./qiskit-jupyter/notebooks:/home/qiskit/qiskit-jupyter/notebooks
      - ./qiskit-jupyter/examples:/home/qiskit/qiskit-jupyter/examples
    ports:
      - 8889:8889
    restart: unless-stopped
