version: "2"
services:
  qiskit-service:
    image: qiskit
    container_name: qiskit-container
    build:
      context: ./
      dockerfile: ./Dockerfile_prod # production environment
    environment:
#      - QISKIT_API_TOKEN=
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./qiskit-jupyter:/home/qiskit/qiskit-jupyter
    ports:
      - 8889:8889
    restart: unless-stopped
